# Generated by Django 3.1.2 on 2020-10-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0005_auto_20201029_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
