# Generated by Django 3.1.2 on 2020-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0007_auto_20201029_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='status',
            field=models.TextField(default='Not Published', max_length=15),
        ),
    ]
