# Generated by Django 3.1.2 on 2020-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0008_wish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='body',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wish',
            name='desc',
            field=models.CharField(max_length=50),
        ),
    ]
