# Generated by Django 3.1.2 on 2020-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0009_auto_20201029_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='body',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wish',
            name='status',
            field=models.CharField(default='Not Published', max_length=15),
        ),
    ]
