# Generated by Django 3.1.2 on 2020-10-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0010_auto_20201029_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
