# Generated by Django 3.1.2 on 2020-10-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0011_auto_20201029_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='reply',
            field=models.TextField(default='Thanks a lot', max_length=250),
        ),
    ]
