# Generated by Django 3.1.2 on 2020-10-29 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0012_wish_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='reply',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishes.wish')),
            ],
        ),
    ]
