# Generated by Django 3.1.2 on 2020-11-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0013_auto_20201029_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='desc',
            new_name='description',
        ),
    ]
